name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use HTTPS instead of SSH for Git cloning
      run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
    - name: Run GitHub Action for ORT
      uses: oss-review-toolkit/ort-ci-github-action@v1
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /home/runner/.ort/ort-results
